
services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
    ports:
      - 8000:8000
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    expose:
      - 27017
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5

